url: https://ekurin.github.io/bostrom-wedding/
baseurl:

# Site settings
title: Johan & Sara 2020
email: wedding@kurin.se
description: "Johan och Saras bröllop 2020"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Erik Kurin
  pic: 1
  position: Brudgummens svåger
  social:
    - title: envelope
      url: mailto:toastmaster@kurin.se
    - title: instagram
      url: https://www.instagram.com/wutangclan/
    - title: facebook
      url: https://www.facebook.com/kurin

- name: Lisa Kurin
  pic: 2
  position: Johans syster
  social:
    - title: envelope
      url: mailto:toastmaster@kurin.se
    - title: instagram
      url: # 
    - title: facebook
      url: https://www.facebook.com/lisa.kurin

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
